swagger: "2.0"
info:
  version: "v1"
  title: "关注/取消关注用户"
  description: "再次调用为取消关注"
paths:
  /v1/content/profile/:profile_id/follows:
    post:
      access:
      parameters:
        - name: "profile_id"
          type: "string"
          in: query
          description: "被关注/取消关注的 Profile ID"
          required: true
      responses:
        "200":
          description: "返回成功"
        "404":
          description: "用户不存在"
        "500":
          description: "内部错误"
      response_body: {
          "code": 0,
          "data": {
            "ok": true
          }
        }

