swagger: "2.0"
info:
  title: "新闻详情"
  description: "新闻详情"
  version: "v1"
paths:
  /v1/content/news/:id:
    get:
      parameters:
        - name: "id"
          type: "integer"
          in: path
          description: "新闻 ID"
          required: true

      responses:
        "200":
          description: "返回成功"
          schema:
            $ref: "#/definitions/news_detail_resp"
        "404":
          description: "新闻不存在"
        "500":
          description: "内部错误"

      request_body:
        type: "json"
        value: /v1/content/news/1
      response_body:
        {
          "code": 0,
          "data":
            {
              "article":
                {
                  "id": 1,
                  "kind": 1,
                  "type": 2,
                  "published_at": 1697193075,
                  "title": "新闻标题",
                  "description": "<p>新闻摘要</p>",
                  "body": "<p>新闻正文</p>",
                  "important": true,
                  "pin": false,
                  "comments_count": 1,
                  "likes_count": 2,
                  "bookmarks_count": 3,
                  "counter_ids": ["BABA.US", "700.HK"],
                  "scopes":
                    { "liked": true, "bookmarked": false, "author": false },
                  "last_edited_at": 1697193075,
                  "images":
                    [
                      {
                        "kind": 0,
                        "url": "https://xxx.png",
                        "link": "",
                        "image_style":
                          {
                            "s_128": "https://xxx.png?size=128",
                            "s_320": "https://xxx.png?size=256",
                            "s_1024": "https://xxx.png?size=512",
                            "original": "https://xxx.png",
                          },
                        "meta":
                          {
                            "width": "128",
                            "height": "128",
                            "file_size": "1280",
                          },
                      },
                    ],
                  "containers":
                    [
                      {
                        "id": 1,
                        "title": "话题",
                        "description": "话题描述",
                        "icon": "https://xxx.png",
                        "cover": "https://xxx.png",
                      },
                    ],
                  "source":
                    {
                      "key": 6,
                      "name": "智通财经",
                      "logo": "https://pub.lbkrs.com/cms/2021/0/HyCurh9ido7eT3f4m7wEecVyWoGTchPk.jpg?x-oss-process=style/128",
                    },
                },
            },
        }

definitions:
  news_detail_resp:
    properties:
      article:
        type: "object"
        description: "[Article](/api/content/article/create_topic#article)"
